name: CI

on: [push]

jobs:
  analyse:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          php_extensions: pcntl zip pgsql gd imap mysql bcmath soap intl ldap msgpack igbinary redis swoole memcached pcov imagick
          # Lock composer to working version.
          # See https://github.com/php-actions/composer/issues/120
          version: 2.8.1

      - name: Run Pint
        uses: aglipanci/laravel-pint-action@latest
        with:
          verboseMode: true

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php_version: ${{ matrix.php }}
